### ISSUE TITLE
tests/lambda.rs's handling of free variables is unsound

### ISSUE THREAD

**Issue by meithecatte** [egraphs-good/egg#234]
The approach presented in this test/example fails if there are any rules that allow rewriting an expression in a way that shrinks the set of variables occurring free in the expression.

For example, if we add this rule:

```rust
        rw!("eq-same";   "(= ?a ?a)"        => "true"),
```

the following testcase passes:

```rust
egg::test_fn! {
    lambda_unsound, rules(),
    "(let x a (app (lam x (= (var x) (var x))) b))"
    =>
    "(= a a)",
}
```

With the naive semantics, this is fine. After all, we have proved that the value of `x` doesn't matter, so there's no issue with replacing it with any other variable. However, there are situations where this breaks down:
 - If there is a type system in the background, rewrites like these break subject reduction
 - in a lazy language where evaluating some subterms is UB, this will "optimize" valid programs into `undef`
 - again in a lazily-evaluated language, depending on the cost function provided to the extractor, it might introduce non-termination

The root cause is that the analysis describes the most optimistic set of free variables from all the expressions we've found representing an e-class, instead of the actual expression at which the rewrite is being applied.

Things would be even worse if there was a situation in which an e-class contains two expressions with disjoint sets of free variables, but I can't think of an example at the moment.

**Comment by yihozhang** [comment]
I actually would like to defend the current `lambda.rs` a little bit. I think it faithfully encodes the equational theory of lambda calculus and nothing more (i.e., no consideration of evaluation order or non-termination). It captures the guarantee that, if we fix all the free variables in the analysis to hold the same values, then all the expressions in this e-class will have the same normal form (note the definition of normal forms does not depend on a particular evaluation strategy).

For the potential non-termination introduced, I think it seems more like an issue of the cost function and the bidirectional equivalence than the free variable analysis: For example, consider the rewrite rule `(- ?a ?a) => 0` with `?a` being a non-terminating expression. If you extract `(- ?a ?a)` instead of `0`, this will lead the extracted program to be non-terminating, regardless of the free variable analysis, right?

But maybe you have other examples where the subject reduction is violated or non-termination can be introduced (under a reasonable cost function)?

**Comment by meithecatte** [comment]
Yeah, good point. There's also cool issues such as rewrites like these being able to introduce entirely unbound variables in distant parts of the program, regardless of the free variable analysis.

I think that, in the end, neither the free variable analysis, or even the general approach of handling free variables as simple nodes like these, is to blame – the same could be observed with things like [Cranelift's e-graph IR](https://github.com/bytecodealliance/rfcs/blob/main/accepted/cranelift-egraph.md).

I believe that if your expressions aren't pure and valid in all contexts, and you don't want to rely on the extractor cost function, then each rule must either:
 - have all variables appearing on the left side also appear on the right side
 - decide that the new right hand side is the best possible (e.g. a constant) and prune everything else from the e-class

Do we have any documentation of this and similar caveats?

**Comment by mwillsey** [comment]
We do not. Perhaps the lambda test suite is the right place for this. I hesitate to offer really any advice on how to deal with binding, since there doesn't really seem to be a general solution yet.

**Comment by mwillsey** [comment]
I'm going to close this for now, then. I think the situation is definitely a little unsatisfactory, but it is at least stable and explainable.
