### ISSUE TITLE
Backend-agnostic LP

### ISSUE THREAD

**Issue by averyanalex** [egraphs-good/egg#263]
What do you think about using something like [good_lp](https://github.com/rust-or/good_lp) for abstraction over the LP library? This will allow libraries other than coin-cbc to be used.

**Comment by mwillsey** [comment]
We don't have plans for this at the moment. Over at https://github.com/egraphs-good/extraction-gym we are messing with new approaches to extraction. Currently evidence suggests that LP extraction isn't very good in most cases, so we would like to develop a new encoding instead of improving the implementation of the existing one.
