### ISSUE TITLE
Add some kind of debugging for run-away patterns

### ISSUE THREAD

**Issue by mwillsey** [egraphs-good/egg#43]

**Comment by bjchambers** [comment]
I thin I may be hitting a run-away pattern. I'm somewhat surprised because it doesn't seem to be hitting the time/iteration limits -- just running forever (AFAICT).

I'm wondering if anything was ever added for this, or if you have any tips for how to figure out which rules are misbehaving and/or find a minimal expression that demonstrates the problem. Trying to wrap my head around how to quickly zero in on the problem so that I can figure out how to address it.
