### ISSUE TITLE
Clarify Analysis ordering

### ISSUE THREAD

**Issue by remysucre** [egraphs-good/egg#75]
The new `Analysis::merge` could use a bit more doc, along the line of: 

`Analysis::Data` must form a partial order. For example, the "constant" analysis for `i32` forms the order `None < Some(x: i32)` for any `x` (but any pair of `Some(x), Some(y)` are not comparable). `merge` modifies `to` to be the least upper bound of `to` and `from`. For example, take `merge(a, b)`: 
1. When `b = None` there is no need to modify `a`, as `b` contains no information (is the bottom of the partial order). We know for sure `b <= a`. 
2. When `a = None` and `b = Some(2)` modifies `a` to be `Some(2)`, as `b > a`. 
3. When `a = Some(1)` and `b = Some(1)` there is no modification. 
4. When `a = Some(1)` and `b = Some(2)` egg should panic, as the points have no LUB (they give conflicting information for what the constant should be). 

Is the above consistent with the implementation? I also can't figure out what the ordering returned by `merge` is supposed to mean from the tests.

**Comment by remysucre** [comment]
I think I'm mostly confused by the following points from the current doc: 

> if a < b, then a should be assigned to b.

Does this mean "a should be modified to b"? 

> if they cannot be compared, then a should be modified.

There are two cases here. If they have a least upper bound, then modify a to the LUB. If not, panic.

**Comment by mwillsey** [comment]
I think I closed another issue about this prematurely. Maybe that explanation helps? https://github.com/egraphs-good/egg/issues/72

**Comment by remysucre** [comment]
> Another way to frame this is that merge should return the partial ordering of the inputs a and b, and it should make a the join of a and b. The ordering should correspond to comparing a with b before you modified a.

That makes sense, and noting that there might not be a join of `a` and `b` would be golden. Given this explanation, I don't think the [`merge`](https://github.com/egraphs-good/egg/blob/4b14701c2324191c15049b375df7a56170fb1a37/tests/lambda.rs#L58) in the lambda test is correct? Because `None` is less than `Some` so the first branch should return `Less`?

**Comment by remysucre** [comment]
To be precise, I would implement it so: 

```
if did_change {
    None
} else if to.constant.is_none() && from.constant.is_some() {
    to.constant = from.constant;
    Some(Ordering ::Less)
} else if to.constant.is_none() && from.constant.is_none() {
    Some(Ordering::Equal)
} else if to.constant.is_some() && from.constant.is_none() {
    Some(Ordering::Greater)
} else {
   panic... // can omit if assume no conflicts 
}
```

I'm wildly guessing `Greater` and `Equal` are treated the same?

**Comment by remysucre** [comment]
The ordering on `free` can also be more precise - it's the reverse of the subset relation (a > b iff b contains a).

**Comment by mwillsey** [comment]
cc @fabric-and-ink (I think I closed that issue prematurely, this should be a relevant discussion) 

@remysucre I think you're are right on both counts. `main` is unreleased so there's no warranty :)

I think we should change the merge type again, and it should clarify this confusion and maybe even make composition easier. What about something like:

```rust
fn merge(&self, left: Self::Data, right: Self::Data) -> (Option<Ordering>, Self::Data);
```

So here the client gets both as owned, and has to produce a whole new one as well as the ordering on the two inputs. If they want to use mutation and return one of the original ones, then that should be fine since they are getting owned data. In the ordering case, they should return one of the inputs unmodified.

Another option would be something like:
```rust
fn merge(&self, left: &Self::Data, right: &Self::Data) -> Result<Ordering, Self::Data>;
```

So here you return an ordering if you can, but you have to produce a whole new one if they are unordered. I like this because the type is a little clearer, but it has the downside of you have to make a whole new data (instead of mutating) in the unordered case.

The former option doesn't have this issue, at the cost of a perhaps slightly more complicated type (it's a little less clear what's going on). Also we would be relying on the optimizer to make sure that moving Self::Data around isn't too expensive, but that should be fine.

Thoughts?

**Comment by remysucre** [comment]
Between these two I'm fine with either, maybe prefer the second because it's harder to mess up. In general I'm still trying to understand how analysis maintenance works, in order to understand the current implementation.

**Comment by bjchambers** [comment]
If `Analysis` required `Data: PartialOrd`, then it seems like it would be possible to only call `merge` when it is necessary (eg., when neither `a < b` or `a >= b`, in which case they need to be modified. This seems somewhat consistent with the statement from the current documentation that merge is "only called when the two datas are unordered in the lattice".

I think it would be possible to say that `PartialOrd` should implement the lattice order, and that `merge(&self, left: Self::Data, right: Self::Data) -> Self::Data` should return a data such that `left <= merge(left, right)` and `right <= merge(left, right)`.

Specifically, requiring the `PartialOrd` on Data may make it easier to specify the "laws" that merge must follow to be consistent with the lattice ordering?

**Comment by mwillsey** [comment]
Semantically that's right: `Data` should be partially ordered. I don't want to add that constraint for two reasons:

1. There are many semi-lattices for a single type, i.e. min or max on numbers
2. Ordering should be a method of `Analysis`, that way a comparison of two `Data`s can refer to things in the `Analysis` itself.

**Comment by bjchambers** [comment]
1. That makes sense. One alternative would be to encourage type wrappers in that case:

```
#[repr(transparent)]
struct MinI64(i64);

impl PartialOrd for MinI64 { ... }
```

How often will the analysis data be a simple number vs. a custom struct (eg., containing free variables, as in the lambda case)? It seems like using a wrapper to define a custom ordering woulddn't be too bad.

2. That makes sense, and it does seem nice to keep it analysis. I wonder if treating it as a two separate methods could make sense? What if there were two methods:

```
/// Return the ordering of the two elements in the lattice partial order.
fn cmp_data(&self, left: &Self::Data, right: &Self::Data) -> Option<Ordering>

/// Return an upper-bound of the two data values.
///
/// Only called when `cmp_data(left, right) == None`.
///
/// Should return a value `merge_data(left, right) = ub` such that `left <= ub` and `right <= ub`.
fn merge_data(&self, left: Self::Data, right: Self::Data) -> Self::Data
```

It seems like splitting them up makes it easier to describe the behavior -- the comparison method just reflects the partial order on the lattice, while the merge operator has to behave a certain way with regards to that ordering. It also clarifies mutability -- the comparison shouldn't mutate, while the merge can. 

It would also be possible to have debug asserts when the data can be cloned (clone the left and right, apply merge, then assert that they compare as expected).

**Comment by mwillsey** [comment]
`Option<Lang>` is the most common `Data`, and that already implements `PartialOrd`.

Separating the two makes sense as well. The difficulty is that sometimes its more efficient to implement them simultaneously. Consider set inclusion or something. Checking subsets takes about the same time as intersecting two sets, and you'd have to do it twice.

**Comment by bjchambers** [comment]
What if they were separated for simplicity, and then a combined version existed in terms of those. In cases like intersecting two sets you could override the additional method for better efficiency? The downside is it would still require implementing the other methods... but on the upside, you could provide debug assertions that verify the behavior of the more complicated `merge` and `upper_bound` are correct compared to `cmp`.

For instance:

```
/// Return the ordering of the two elements in the lattice partial order.
fn cmp_data(&self, left: &Self::Data, right: &Self::Data) -> Option<Ordering>

/// Return an upper-bound of the two unordered data values.
///
/// Only called when `cmp_data(left, right) == None`.
///
/// Should return a value `merge_data(left, right) = ub` such that `left <= ub` and `right <= ub`.
fn merge_data(&self, left: Self::Data, right: Self::Data) -> Self::Data

/// Return the upper bound of `left` and `right`.
///
/// The default implementation uses `cmp_data` and `merge_data`.
/// Override this if you can provide a more efficient combined efficiently.
fn cmp_merge_data(&self, left: Self::Data, right: Self::Data) -> (Option<Ordering>, Self::Data) {
  let ord = self.cmp_data(&left, &right);
  let result = match ord {   
    None => self.merge_data(left, right))
    Some(Ordering::Less) => right 
    Some(Ordering::Equal) => left
    Some(Ordering::Greater) => left
  }
  (ord, result)
}
```

**Comment by mwillsey** [comment]
I like this idea. @remysucre thoughts?

**Comment by remysucre** [comment]
I like this too! Thanks @bjchambers !

**Comment by mwillsey** [comment]
@bjchambers could you submit a PR? I can get around to it in a week or so if not.

**Comment by bjchambers** [comment]
I'll try to take a stab at it, but can't guarantee how much time I'll have.

One difficulty that seems to arise is that the above API doesn't fit the use. Since it is modifying values in the hashmap it is only possible to get a `&mut` reference to them. Some options:

- Change the proposed API so that `merge_data` and `cmp_merge_data` still take `left: &mut Self::Data`.
- Require that `Self::Data` implements `Default`. That would allow us to use `std::mem::take(...)` to temporarily put the default value. For example, it would put an empty set in for the class, then run the merge, then the put the result in place.
- Require that `Self::Data` implements `Clone`. This would require cloning the left side before attempting the merge, which seems undesirable, especially in the case of unnecessarily cloning a potentially large set, etc.
- Use `self.classes.entry(id).and_replace_entry_with(...)`. This provides owned access to the entry, but leads to additional complexity, since it can't easily append to the `self.analysis_pending` set within the replacement function.

Any preferences? I went down the route of `and_replace_entry_with(...)` initially but that leads to some pain. The `Default` seems like the simplest option, with the application being something like:

```
let class1_data = std::mem::take(&mut class1.data);
let (ord, data) = N::cmp_merge_data(class1_data, class2.data);
class1.data = data;
```

But at first glance it may negatively affect performance. I can poke at it some more. Otherwise, my thinking is that it may make sense to keep the `&mut` but maybe with the separate methods it is clearer to document?

Another option that occurred to me after seeing `merge_min` and `merge_max` is that it could keep the single method, but there could be different versions of those helpers. For instance, if we had:

```
trait DataLattice {
  /// Return the ordering between the elements (if any) in the lattice.
  ///
  /// This is equivalent to `partial_cmp`, but part of DataLattice so that it is explicitly
  /// implemented in a way that is consistent with `merge`.
  def lattice_cmp(&self, other: &Self) -> Option<Ordering>

  /// Returns a merged point in the data lattice. This should satisfy:
  /// `a <= a.merge(b)` and `b <= a.merge(b)`. 
  ///
  /// This only needs to handle the case where `a` and `b` are unordered.
  def merge(self, other: Self) -> Self;

  /// Mutable version of `merge` which updates `self` to contain the merged value.
  /// Should satisfy the same ordering rules.
  def merge_into(&mut self, other: &Self);
}

/// Updates `to` be an upper bound on `to` and `from`, and returns the original
/// ordering between  `to` and `from`.
fn merge_lattice<T: DataLattice>(to: &mut T, from: T) -> Option<Ordering> {
  let ord = to.lattice_cmp(from);
  match ord {
    None => merge_into(to, from),
    Some(Ordering::Less) => *to = from,
    Some(Ordering::Equal) | Some(Ordering::Greater) => {},
  }
  ord
}
```

Benefits of this over the original proposal:

1. There is only one method on the `Analysis` trait. If you can implement it directly, you can use that.
2. If it is easier to construct your data as a lattice, you can use the existing partial order. But you need to choose to implement `DataLattiice`, so it won't unintentionally pick up the default ordering of numbers without it being clear. We could even have a differently named method on `DataLattice` if we really wanted to decouple it.
3. It is possible to provide implementations for common tuples, making it easier to compose lattice operations.

```
// Could default to either point-wise or lexicographic order.
impl<A: DataLattice, B: DataLattice> DataLattice for (A, B) {
   ...
}
```

**Comment by mwillsey** [comment]
I'm not sold on an additional trait yet. I like keeping it all under Analysis for now, especially since that allows all methods to access the analysis itself.

What's wrong with the `self.classes.entry(id).and_replace_entry_with(...)` approach? It should only require `&mut` on `classes`, and you should be able to `self.analysis_pending` just fine. You may have to split the borrows so the closure doesn't capture `self`.
```rust
let a_pending = &mut self.analysis_pending;
self.classes.entry(id).and_replace_entry_with(|...| {
 // use a_pending but not self
})
```

**Comment by mwillsey** [comment]
Also, we should close this issue since we answered the question. @bjchambers can you open a draft PR and we can continue there?
